spring.datasource.url=jdbc:postgresql://localhost:5432/springcore
spring.datasource.username=postgres
spring.datasource.password=/3042000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
